name = "DAM"
author = "Danny Le"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bebc56648c30c4255848f8df39f6ad39f89f3fa7f162aa5df71a437d192827c2"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
