name = "DAM"
author = "Danny Le"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3665b4f37bf0c1674d1cb9e959fe49e6dcb95ac88409b9f61d90c9d7e7a1b8b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
