name = "DAM"
author = "Danny Le"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bb1313c865a1af6ee4d43af3cd548c16b016e028a8b8e2cf1e838166393c905"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
