name = "DAM"
author = "Danny Le"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a6259ddc7ab94679f8cee38f900511c2041ff39b0375138033c5a50d0da58c2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
