name = "DAM"
author = "Danny Le"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c1b4c50b8a86b70515457a9cdc2bee76162cafe3db1657c9f4c6cc0d8e8178b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
