name = "DAM"
author = "Danny Le"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1907e456f92a2cfe1a53fb7a22f4a19a53fd3e66b4654697773da4b1efb07f2e"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"
