name = "DAM"
author = "Danny Le"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a5fa98be2a54aef51e09a52bf8e16530b3b10bc98e4fbc329e8db64bbb63a4d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
