name = "DAM"
author = "Danny Le"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba0d722eccb893e2f1bf6083a18309c6a9a15181bab571396340a0cdb7c7a605"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
