name = "DAM"
author = "Danny Le"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68ae0600adeab26d367af65ca86a619a936375ef1db6b542f1a6dbdf4f757b1b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
