name = "DAM"
author = "Danny Le"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac0b799b275264cc6afafc00ff70895f68ce5ca0de9192129f3cdbe716af11f9"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
