name = "DAM"
author = "Danny Le"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "197f415a63a4cfc9a15d9edcdc39497733b71accbd03980a39d6628fc331f085"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
